name: CI for Static Website

on:
  push:
    branches:
      - main   # Trigger the workflow on push to main branch
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate HTML & CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5-validator-action@v1.7.1
        with:
          file: "index.html"  # Adjust this if validating multiple files

      - name: Validate CSS
        uses: josephdust/css-validator-action@v1
        with:
          css_file: "styles.css"  # Removed dot prefix, make sure path is correct

