name: CI for Static Website

on:
  push:
    branches:
      - main   # Trigger the workflow on push to main branch
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate HTML & CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5-validator-action@v1
        with:
          file: "DEV/WorkBased/index.html"  # Path to your HTML file

      - name: Validate CSS
        uses: josephdust/css-validator-action@v1
        with:
          css_file: "DEV/WorkBased/styles.css"  # Path to your CSS file

  deploy:
    name: Deploy to GitHub Pages
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload files
        uses: actions/upload-pages-artifact@v1
        with:
          path: DEV/WorkBased  # Folder to publish on GitHub Pages
