name: PHP CI/CD with Lightweight IaC

on:
  push:
    branches: [main]

jobs:
  php-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml

      - name: Lint PHP files
        run: find . -type f -name "*.php" -exec php -l {} \;

  staging-deploy:
    runs-on: ubuntu-latest
    needs: php-ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to staging via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_STAGING_SERVER }}
          username: ${{ secrets.FTP_STAGING_USERNAME }}
          password: ${{ secrets.FTP_STAGING_PASSWORD }}
          server-dir: /staging/

  production-deploy:
    runs-on: ubuntu-latest
    needs: staging-deploy
    environment:
      name: production
      url: https://your-production-url.com
    steps:
      - name: Manual approval required
        uses: peter-evans/slash-command-dispatch@v2 # Alternative: GitHub Environments manual approval
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
